### PR TITLE
Enhancements by @farnoux and @antham

### PR DESCRIPTION
**Pull request by tschaub**
This merges in changes from the [iAdvize fork](https://github.com/iadvize/github-changelog).

After merging this, If @farnoux and @antham are willing, I'll transfer ownership of this repository to @iadvize (I assume this will only work if they rename or delete their fork first).

### CODE REVIEW

**Comment by antham** [comment]
Hi,
thanks for your proposal, we are interested to take over the ownership of this repository, let us know when you are ready.

**Comment by tschaub** [comment]
@antham if you rename the https://github.com/iadvize/github-changelog to something else, I'll transfer ownership of this one to @iadvize.

**Comment by antham** [comment]
Hi, we renamed our repository, we are ready.

**Comment by tschaub** [comment]
@antham and @iadvize - apologies for the delay on this.  It looks like I cannot transfer the repository as long as you have a fork of this repository (regardless of the name).  Since the iadvize/iadvize-github-changelog repo is a fork of this one, I cannot transfer this one to @iadvise.

I'd like to transfer this if you are willing to carry on with its development.  This should be possible if you delete the iadvize/iadvize-github-changelog repo - you should be able to create a new one and push the same commits there.

**Comment by antham** [comment]
In the meantime, we wrote a brand new tool to handle changelog, so we no longer use this app.

**Pull request merged**
